### ISSUE TITLE
Steam hangs after login with esync

### ISSUE THREAD

**Issue by funghetto** [bobwya/bobwya#34]
Can you reproduce? Is it a problem in upstream wine esync?

**Comment by bobwya** [comment]
TBH it's a very low priority for me to test or fix this. Don't expect anything to happen about this issue anytime soon.

I am regretting bothering to add **esync** and **pba** support. The latter (obviously) because it is unsupported and is already broken, with respect to newer Wine versions (>3.18). The former because it introduces issues (for me) when launching applications, even when the **WINEESYNC** env variable is unset (which basically shouldn't happen).

**Comment by funghetto** [comment]
Ye I saw your bug report on pba, sad to see that it got inactive.

Another problem I have with esync is that some of the wine's own .exe processes get unkillable.

**Comment by funghetto** [comment]
I tried to emerge an older wine version with both ESYNC and PBA and there steam works and the processes get shut down correctly, so maybe the correct thing should be to remove ESYNC from the last wine versions like you did with PBA?

**Comment by bobwya** [comment]
@funghetto I know ZF rebased esync recently - which is required for it to work with newer versions of Wine. The real problem is that it way too big (83 patches)! I'll probably have to look at squashing the patchset to a 1 patch file per 1 wine source file like how I (_don't_) support wine-pba.

I'm currently doing some refactoring of the **app-emulation/wine-*** ebuilds to use a separate eclass, Then I plan to integrate **faudio** support. After that I _may_ revisit **esync** support.

**Comment by bobwya** [comment]
@funghetto I pushed a **wine-esync** refresh... Rebasing the newer **app-emulation/wine-staging** and **app-emulation/wine-vanilla** versions on: [esyncce79346](https://github.com/zfigura/wine/tree/esyncce79346).

I'm personally still seeing issues, e.g. like I cannot open the Steam client, with **WINEESYNC** enabled or unset. But even with stock Wine Staging I have some issues, like exceptions being raised during the Steam Client startup. (With Steam overridden to **Windows 2003**).

I've split the **wine-esync** patches into a per-file (Wine Source) patch (without the **wine-esync** revision history). So it should be easier to test out changes to the **wine-esync** source. This is obviously harder to do, when you have a base **wine-esync** patchset (pre-release version) and a separate rebasing patchset.

I'm inclined to leave the patchset in my ebuild. It was developed by ZF (a very active Wine Developer), who is employed by Codeweavers... So this project differs from **wine-pba**, which was obviously much more of a "throw it over the wall" approach. The issue with **wine-esync** is timing relationships... It's clearly much more prone to deadlocks, than stock Wine. I'll see if I can report any bugs Upstream, once I've taken a closer look at the code.

I think the benefits of having more people testing **wine-esync**, outweigh the problems... Especially, since on Gentoo you can build multiple copies of a **app-emulation/wine-staging** / **app-emulation/wine-vanilla** package version (both with and _without_ the **esync** patchset). Or simply omit **esync** support completely (by disabling the USE flag).

Obviously I'll leave this issue open... But it does appear to be more of an Upstream issue, IMHO.

**Comment by funghetto** [comment]
Good job.
Indeed, if the project is still active and we can keep up with it, it is better to still have the flag around.

**Comment by funghetto** [comment]
Weird, I still have this problem with your wine while using esync from Lutris's tkglitch wine works fine.
