### ISSUE TITLE
eselect-wine no longer works on 17.1 profile

### ISSUE THREAD

**Issue by aTosser** [bobwya/bobwya#42]
```
# eselect wine list
Available 'wine' versions:
  [1]   wine-staging:3.21
  [2]   wine-staging:4.0
  [3]   wine-staging:4.1
  [4]   wine-staging:4.1_p1
  [5]   wine-staging:4.3
  [6]   wine-staging:4.4
  [7]   wine-staging:4.7
  [8]   wine-staging:4.8
  [9]   wine-staging:4.9 *
# eselect wine set 9
Symbolic link ('/usr/lib32/libwine.so') not found for 'wine'
Symbolic link ('/usr/lib32/libwine.so.1.0') not found for 'wine'
Symbolic link ('/usr/lib32/libwine.so.1') not found for 'wine'
Symbolic link ('/usr/lib64/wine') not found for 'wine'
```

**Comment by bobwya** [comment]
@aTosser 

The implementation is designed to be fairly robust. Obviously in your case **eselect-wine** is failing, when trying to remove the previously set symbolic links, for the (main) **wine** variant. This is bound to happen - since all of the (32-bit) symbolic links have been moved to new locations, during the profile update!

I think that running:

    eselect wine set --force 9

will work around this: by ignoring non-existant symbolic links and then forcibly overwriting the pre-existing symbolic links - which were moved (during the profile update).

Obviously if you bother to use the **staging** and **vanilla** variants (personally I don't) - then the process would need to be repeated for these.
