### ISSUE TITLE
Leave Stable Wine as Stable and Development as Development

### ISSUE THREAD

**Issue by jorgicio** [bobwya/bobwya#5]
Hi!

Thanks for the overlay. However, as a suggestion, you could leave the stable version of Wine (1.8) as the latest stable, because 1.9 branch is the development one (so I think the latest must have the "~").

Anyways, thank you!

**Comment by bobwya** [comment]
Jorgicio,

This hack:
```
let "MINOR_V_ODD=$(get_version_component_range 2) % 2"
MY_PV="${PV}"
if [[ "$(get_version_component_range 3)" =~ ^rc ]]; then
    MY_PV=$(replace_version_separator 2 '-')
elif [[ ${MINOR_V_ODD} == 1 ]]; then
    KEYWORDS="-* ~amd64 ~x86 ~x86-fbsd"
else
    KEYWORDS="-* amd64 x86 x86-fbsd"
fi
```

... automagically sets:
1.Wine  __rc versions__ as un-keyworded
2. Wine __development__ branch releases (odd minor) as unstable keyworded (all supported platforms)
3. Wine __stable__ branch releases (even minor) as stable keyworded (all supported platforms)

Not sure what else is required?? Perhaps you could clarify?

Perhaps you haven't sync'd the Overlay since I altered this (although it's been a few days since I last altered the Overlay)?

Bob

**Comment by jorgicio** [comment]
You're right. I didn't sync correctly, just this overlay. Then I synched everything and working.

Thank you!

**Comment by bobwya** [comment]
np __:-)__
