### ISSUE TITLE
ebuild failed to build

### ISSUE THREAD

**Issue by mik1osh** [bobwya/bobwya#6]
emerge -auNDv =firefox-kde-opensuse-47.0.1

These are the packages that would be merged, in order:

Calculating dependencies                L * ERROR: www-client/firefox-kde-opensuse-47.0.1::bobwya failed (depend phase):
 *   mozconfig-v6.47.eclass could not be found by inherit()
 * 
 * Call stack:
 *                            ebuild.sh, line 606:  Called source '/var/lib/layman/bobwya/www-client/firefox-kde-opensuse/firefox-kde-opensuse-47.0.1.ebuild'
 *   firefox-kde-opensuse-47.0.1.ebuild, line  39:  Called inherit 'check-reqs' 'flag-o-matic' 'toolchain-funcs' 'eutils' 'gnome2-utils' 'mozconfig-v6.47' 'pax-utils' 'fdo-mime' 'autotools' 'virtualx' 'mozlinguas' 'mercurial'
 *                            ebuild.sh, line 279:  Called die
 * The specific snippet of code:
 *              [[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=www-client/firefox-kde-opensuse-47.0.1::bobwya'`,
 * the complete build log and the output of `emerge -pqv '=www-client/firefox-kde-opensuse-47.0.1::bobwya'`.
 * Working directory: '/usr/lib64/python3.4/site-packages'
 * S: '/var/tmp/portage/www-client/firefox-kde-opensuse-47.0.1/work/firefox-kde-opensuse-47.0.1'
... done!

**Comment by bobwya** [comment]
Hi **mik1osh**,

I haven't pushed an update to firefox-kde-opensuse 48.0 because I'm hard at work completely re-factoring the **ebuild** 's:

- enabling true EAPI 6 support throughout
- creating cloned copies of the **mozconfig** **eclass** (renamed to avoid conflicts)
- tidying up my patching script (hack!!)

I should be able to push an update v. soon that will fix your issue and by creating cloned copies of the Mozilla **eclass** I'll totally avoid this issue happening in the future!! The problem / delay is I have to simultaneously fix the **thunderbird-kde-opensuse** package.

In the meantime / on temporary basis - to get you up and running **now** -  you can pickup the missing **eclass** from the Calculate Overlay... Just down and drop it in to your main **eclass** directory:
```
cd /usr/portage/eclass
wget -c "http://data.gpo.zugaina.org/calculate/eclass/mozconfig-v6.47.eclass"
```
(the _default_ location for your Gentoo **eclass** 's - change the path if necessary!!)

So **tl;dr** I am aware of the issue and I'm working on a permanent fix!!

**Comment by bobwya** [comment]
I've sync'd my Overlay with more permanent fixes for the package **www-client/firefox-kde-opensuse**. I've added clone's of the main Mozilla **eclass** files to my Overlay. So hopefully this problem won't re-occur!!

Just open a new issue if you've still got any problems :-)

**Comment by mik1osh** [comment]
error gone, thank you!

**Comment by bobwya** [comment]
np... Hopefully things will be smoother going forwards :-)

**Comment by bobwya** [comment]
Just a quick further note to say I've finished re-factoring the cloned Mozilla eclass's now (renamed to avoid any name-space conflicts) and re-added support for the package **mail-client/thunderbird-kde-opensuse**. Sorry - I've actually been meaning to fix this issue - ever since I first developed the package!!

No need to rebuild **www-client/firefox-kde-opensuse**. The changes are really just "under-the-hood" and will (after all) be pulled next time you sync this Overlay!!
