### ISSUE TITLE
=www-client/firefox-kde-opensuse-48.0 failed to build

### ISSUE THREAD

**Issue by mik1osh** [bobwya/bobwya#7]
emerge www-client/firefox-kde-opensuse | wgetpaste
Your paste can be seen here: http://bpaste.net/show/58fc3261247e

I have no idea what is wrong =(

**Comment by bobwya** [comment]
Sorry 'bout the delay - other work getting in the way. I still had some lingering **eclass** bugs creeping in... That's the main error I'm seeing in your build log - well apart from those pesky sandbox violations :-) ...

I guess my English locale meant I was missing this - since the build tests succeeded (but with build log warnings I didn't notice).

I've not rev-bumped anything - since the fixes are relatively minor. So try re-syncing the Overlay and see if the package builds now.

**Comment by mik1osh** [comment]
I tried again and got the same 13k lines of error messages
maybe it's because I use kde4/qt4?

**Comment by bobwya** [comment]
Yes, there is that... I'm using the Qt 5 build of **kmozillahelper** with Plasma 5.
But the build errors do look perhaps more due to building as an unprivileged user or something like that perhaps? I build all my packages as the stock **portage** user/sandbox...

The newer build log **should** be at least slightly different - as I've fixed the **mozlinguas** **eclass** bug. I wasn't sure if it was the only problem you had - but it needed to be corrected anyway...

I don't build with all of the **USE** **system-...** flags enabled (see below for what I do trust!!) - basically because Mozilla software is flaky as hell... It's liable to break/ fail to build - if you try to link it against your system libraries!! Plus I build using the older **gtk2** (toolkit) **USE** flag - mainly because the **gtk3** doesn't play ball with the breeze theme on Plasma 5 (but **gtk3** support does appear to cause other oddness).

For your reference:
```
emerge -pv firefox-kde-opensuse
[ebuild     R ~] www-client/firefox-kde-opensuse-48.0::bobwya USE="dbus gmp-autoupdate gtk2 hardened hwaccel jemalloc3 jit kde pulseaudio skia startup-notification system-icu system-jpeg system-sqlite wifi -bindist -custom-cflags -custom-optimization -debug (-neon) -pgo (-selinux) -system-cairo -system-harfbuzz -system-libevent -system-libvpx {-test}"
```

**Comment by mik1osh** [comment]
yes, about kde4 it seems so, because without "-kde" USE flag browser build corretly (but winthout kde files dialogs)
thus it can be concluded that kde4-support is completed on 47 version, which is a pity

anyway thank You for support qt4-build of firefox for all this time

**Comment by bobwya** [comment]
There's this oddness, in the original build file:
```
Error: "/root/.kde4/tmp-humgat" points to "/tmp/kde-root" instead of "/var/tmp/portage/www-client/firefox-kde-opensuse-48.0/temp/kde-root".
 * ACCESS DENIED:  unlink:       /root/.kde4/tmp-humgat
 * ACCESS DENIED:  symlink:      /root/.kde4/tmp-humgat
Error: Can not create link from "/root/.kde4/tmp-humgat" to "/var/tmp/portage/www-client/firefox-kde-opensuse-48.0/temp/kde-root"
 * ACCESS DENIED:  unlink:       /root/.kde4/tmp-humgat
 * ACCESS DENIED:  symlink:      /root/.kde4/tmp-humgat
Error: Can not create link from "/root/.kde4/tmp-humgat" to "/var/tmp/portage/www-client/firefox-kde-opensuse-48.0/temp/kde-rootoj8A1t"
Error: "/root/.kde4/socket-humgat" points to "/tmp/ksocket-root" instead of "/var/tmp/portage/www-client/firefox-kde-opensuse-48.0/temp/ksocket-root".
 * ACCESS DENIED:  unlink:       /root/.kde4/socket-humgat
 * ACCESS DENIED:  symlink:      /root/.kde4/socket-humgat
Error: Can not create link from "/root/.kde4/socket-humgat" to "/var/tmp/portage/www-client/firefox-kde-opensuse-48.0/temp/ksocket-root"
 * ACCESS DENIED:  unlink:       /root/.kde4/socket-humgat
 * ACCESS DENIED:  symlink:      /root/.kde4/socket-humgat
Error: Can not create link from "/root/.kde4/socket-humgat" to "/var/tmp/portage/www-client/firefox-kde-opensuse-48.0/temp/ksocket-rootVVURfs"
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
KLauncher: Fatal error, can't create tempfile!
kdeinit4: Communication error with launcher. Exiting!
kmozillahelper(15231): No ksycoca4 database available! 

kmozillahelper(15231)/kdecore (trader) mimeTypeSycocaOffers: KMimeTypeTrader: mimeType "application/javascript" not found 
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
KLauncher: Fatal error, can't create tempfile!
kdeinit4: Communication error with launcher. Exiting!
kmozillahelper(15231): No ksycoca4 database available! 
```
Which leads to a build sandbox violation. I can reproduce this on my system - by building against the **Qt4**-based **mozillahelper** utility... So I'll look into what part of the install process Portage thinks it would be a good (i.e. bad!!) idea to launch the **mozillahelper** utility, as **root**, over **dbus**!!

I'll "go dark" again - till I've resolved this issue to my satisfaction... :-)

**Comment by bobwya** [comment]
Ok, so I'm really getting lost in the weeds here... I'll have to ping Wolfgang over this one! I just don't understand the install phase at all...

In the meantime I'd use an **env** override for Portage just so you can continue to build and use the package (with a **KDE 4** file dialog):
```
cat /etc/portage/env/nosandbox.conf
FEATURES="${FEATURES} -sandbox -usersandbox"

cat /etc/portage/package.env/firefox-kde-opensuse 
www-client/firefox-kde-opensuse         nosandbox.conf
```

**Comment by mik1osh** [comment]
wow! it works for me!

and may need to make two different USE flags in the ebuild file - one for kde4 and one for kde5?

**Comment by bobwya** [comment]
No I don't need separate USE flags! I'd need to actually fix the sandbox violation that's occurring. My suggestion, **env** overrides, is only a hacky workaround and is generally not a recommended practice! Especially since  it opens security holes, etc (since the root file system is accessible throughout the entire build process).

But here's the thing... I don't know how long it'll take to chase the issue down. The Mozilla codebase a sprawling pile of poo... They seem to think it's acceptable to leave a crap-tonne of compiler warnings unpatched...

I'll leave the issue open till I've got a "real fix" in the works...

**Comment by bobwya** [comment]
Okay... So first try at a simple - but less dirty fix... I've pushed a small patch to **=kde-misc/kmozillahelper-0.6.4** so it will refuse to run as the **root** user. That stops all the sandbox violations on my system.  The **kmozillahelper** process is started by the Mozilla installer (**wtf** - why?>!?!) and then immediately exits. So it won't try to touch / update (bad touch!!) KDE cache locations, etc.

See if that will also work on your system... I know you're using a **userenv** build. But I believe the install phase will still run as _root_ (when the sandbox violations occur)...

Anyway... So take it for a spin!

1. Backup / Disable your **env** override (to disable sandboxing)
2. Sync the Overlay
3. Emerge **=kde-misc/kmozillahelper-0.6.4-r1**
4. Re-test emerge'ing **=www-client/firefox-kde-opensuse-48.0**

**Comment by mik1osh** [comment]
works for me
thanks!

**Comment by bobwya** [comment]
> works for me thanks!

Oops... Yeah forgot to mention I closed the Issues thread by accidently pressing the wrong button before... :-)
Glad to hear that workaround does actually "fix" the issue!
